name: Github Publish

on:
  workflow_dispatch:
#  push:
#    branches:
#      - 'floss'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v2
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: build.yml
        workflow_conclusion: success
        branch: floss
        name: release.apk
        path: downloads
        if_no_artifact_found: fail

      # 8
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: downloads/release.apk
